### ISSUE TITLE
Crash while walking through a BYG Rose Field

### ISSUE THREAD

**Issue by MScott7** [MUYUTwilighter/saplanting_fabric#10]
Hi, my game has crashed and now keeps crashing when I relaunch. I was walking through a Rose Field from Oh The Biomes Youll Go. Some water was breaking some rose bushes so maybe they tried to replant themselves. 

Latest.log (it's really long but you can click "view the full file"): https://gist.github.com/MScott7/a20dbb6d39ec2efaaaf79013bf46b0bd

Minecraft version 1.18.2
Fabric version 0.14.9
Fabric API version 0.58.0
Saplanting version 1.18.2-1.1.3+1
BYG version 1.18.2-1.4.4

Rose Fields: https://oh-the-biomes-youll-go.fandom.com/wiki/Rose_Fields

Let me know if there's any more info I can provide

**Comment by MUYUTwilighter** [comment]
I have test it on my own and find the reason, the fixed version should be released in few days.  
Before the new version is available, you may have to turn off "allowFlowers" or some properties like that so that you can continue your game. :D

**Comment by MScott7** [comment]
I just double-checked my config file and allowFlowers is set to false, I don't remember changing any Saplanting settings so that's the default, right? I can try changing plantLarge or other properties though. Thanks for the quick reply :)

**Comment by MUYUTwilighter** [comment]
> I just double-checked my config file and allowFlowers is set to false, I don't remember changing any Saplanting settings so that's the default, right? I can try changing plantLarge or other properties though. Thanks for the quick reply :)

Well, I had tested on my own client, and operations I've mentioned above is available to resolve the problem. Maybe there are other problems but the log file you provided contains no crash-info(maybe result from not-enough-crashes), so I cannot figure out what actually caused the crash.  
But no worry, I have complete a overall rewrite of Saplanting, and the problem no longer appears here. The new version will be released soon! 👍

**Comment by MUYUTwilighter** [comment]
Newer version is released and you can run your client with [this](https://github.com/MUYUTwilighter/saplanting_fabric/releases/download/1.2.0/saplanting-fabric-1.18.2-1.2.0.jar) as a test!
