### ISSUE TITLE
All saplings revert to oak sapling.

### ISSUE THREAD

**Issue by Linusintro** [MUYUTwilighter/saplanting_fabric#14]
All saplings lying on the ground and get planted revert to an oak sapling. Even other types of sapling like acacia.

**Comment by Linusintro** [comment]
This is in version 1.12.2 Forge.

**Comment by MUYUTwilighter** [comment]
Issues on forge should be posted on dedicated repository
https://github.com/MUYUTwilighter/saplanting_forge

Anyway, your issue is received and assigned
