### ISSUE TITLE
Modrinth 1.2.6 只标记为了 1.20.2 版本，请添加下 ~1.20

### ISSUE THREAD

**Issue by SettingDust** [MUYUTwilighter/saplanting_fabric#17]

**Comment by MUYUTwilighter** [comment]
没有标注其他版本是因为我没有在（也不打算）为其他小版本做测试。
mod元数据并未给小版本作强制限制（1.19.X 除外，详见 #9 ），如果你有需要，尽可以将本模组运行在你需要的 MC 版本上

本人开发的 mod 项目在一般情况下只对部分大版本的 **最终或最新小版本** 进行持续性维护，如果你发现你需要的 MC 小版本不再受支持且认为我有足够理由来维护你需要的这个版本，请单独提交 "Version&Loader" 的 issue 并在其中详细说明理由

**Comment by SettingDust** [comment]
测试了一下 1.20.1，运行没问题
