### ISSUE TITLE
Port 1.2.6 that fix saplings incorrectly placing to 1.20.1

### ISSUE THREAD

**Issue by PolyframeX** [MUYUTwilighter/saplanting_fabric#19]
When an item drops, a sapling is created that cannot be destroyed until the item is removed.

It is unknown how to reproduce this bug. But it is quite annoying and causes lag in certain scenarios.

[Video](https://drive.google.com/file/d/1Je7CQKou1ht1oc-A8lLaMcm9BgC-J77S/view?usp=sharing)

Mod version: 1.2.5

Fabric version: 0.15.7

**Comment by MUYUTwilighter** [comment]
This issue has already been fixed in 1.2.6.
