### ISSUE TITLE
The sapling teleportation will plant in the sky

### ISSUE THREAD

**Issue by zc1108aaa** [MUYUTwilighter/saplanting_fabric#20]
![2024-05-30_20 33 24](https://github.com/MUYUTwilighter/saplanting_fabric/assets/155424398/91209a78-5337-40e0-9379-3bb35a9bae99)

**Comment by MUYUTwilighter** [comment]
详细说一下你是怎么tp的

**Comment by zc1108aaa** [comment]
出生点命令方块/TP @E [TYPE=ITEM] X Y Z

**Comment by MUYUTwilighter** [comment]
MC版本、mod版本等详细信息提供出来，参见 #5

**Comment by zc1108aaa** [comment]
Fabric：0.15.11
Fabric API：fabric-api-0.92.1+1.20.1
Saplanting：-fabric-1.20.1-1.2.6

**Comment by MUYUTwilighter** [comment]
我这边没有测试出相关问题，是否有其他触发条件？

**Comment by MUYUTwilighter** [comment]
No more information and I can't replicate this bug, so I close this issue
