### ISSUE TITLE
[Suggestion] only 2x2 dark oak trees

### ISSUE THREAD

**Issue by energy11a** [MUYUTwilighter/saplanting_fabric#3]
Add option to allow only 2x2 dark oak planting.

**Comment by MUYUTwilighter** [comment]
Great idea. But temporarily I'm focusing on improving the performance, via reducing the pressure caused by this mod.
Some related features were already in schedule, probably they will be added in Saplanting v1.2

**Comment by MUYUTwilighter** [comment]
BTW, such suggestions are highly recommended to be pulled in "Pull Request" page.
I'd appreciate if you re-pull this suggestion on that page.

**Comment by MUYUTwilighter** [comment]
This feature was added in Saplanting 1.1.3 for 1.19.2 Fabric, thanks for giving this suggestion!
