### ISSUE TITLE
Crashing while wandering around

### ISSUE THREAD

**Issue by TheButterbrotMan** [MUYUTwilighter/saplanting_fabric#4]
https://bytebin.lucko.me/vyNWVnpOuB

**Comment by MUYUTwilighter** [comment]
Too few information, and such issue will not be adopted.

**Comment by TheButterbrotMan** [comment]
> Too few information, and such issue will not be adopted.

If you need more information, just ask. I'm willing to provide.

The log hast all technical information you need. 

If you want some basic kind of information because you are to lazy to read out of the log, you should setup a formular.
