### ISSUE TITLE
100% CPU usuage on server while using this mod.

### ISSUE THREAD

**Issue by seanimusprime** [MUYUTwilighter/saplanting_fabric#7]
This mod was causing my server to use 100%+ of my available CPU usage. Here is a spark profiler report that might have some useful information in it:
https://spark.lucko.me/dSKHpZIx6u

**Comment by MUYUTwilighter** [comment]
Sorry, please tell me which version of the mod that you're using and this phenomena occurred, at least, along with the mod list you're using.
BTW, a log and a crash report(if there is) are also helpful.
Please check "Good first issue" and post some useful information mentioned above.

**Comment by MUYUTwilighter** [comment]
Your description is likely to mention the performance issue of Saplanting 1.1.2 for 1.19, and this bug is fixed in Saplanting 1.1.2+1.  
If I misunderstood, or some other errors are occurring, please let me know here.  
If no reply, this issue will be closed in 2 days.
