### ISSUE TITLE
Images on project page are not loading due to 403 errors for non-Chinese users

### ISSUE THREAD

**Issue by James103** [MUYUTwilighter/saplanting_fabric#8]
On the project page of this mod, https://modrinth.com/mod/saplanting, there are 3 images.
These images do not load properly for non-Chinese users because they are hosted on a Chinese website that blocks all requests made by non-Chinese users or anyone outside China.

The images should be moved (rehosted) to a website that allows almost all users to view the image. For example, this Github repository, imgur, imgbb, or similar.

**Comment by MUYUTwilighter** [comment]
OK, I'll move the pics to somewhere non-Chinese users could surf them.  
Before I finish that, you can use VPN or something else to view the images.
